### ISSUE TITLE
ビルドシステムを用いた組立

### ISSUE THREAD

**Issue by RotationE** [RotationE/NeoC#7]

**Comment by pTvTq** [comment]
今のところ単なるシェルスクリプトで十分では？

**Comment by Hiroya-W** [comment]
面白いライブラリでした！
ビルドスクリプトで、少し気になったところがあったので書いておきます。

## shはbashではない場合がある

例示されているビルド方法は、以下の方法でしたが、

```bash
$ sh build.sh
```

build.shの中身はbash scriptなので、bashで実行する必要があると思います。
例えば、shはdashのエイリアスである場合があり、こういった環境で動かない問題がありました。

```bash
$ ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Jun 21 00:00 /bin/sh -> dash
```

[シェルスクリプトでSyntax error: "(" unexpectedの対処法（Ubuntu） - /var/www/yatta47.log](https://yatta47.hateblo.jp/entry/2014/04/20/222707)

これを回避するために、スクリプトの呼び出しは以下のようにするべきだと思っています。
build.shの中でexamples/build.shを呼び出しているところも同様です。

```bash
$ bash build.sh
```

もしくは、build.shにshebangを書いておいて

```bash
#!/bin/bash
...
```

```bash
$ chmod +x build.sh
$ ./build.sh
```

とするようにしても良さそうでした。

## sedのバイナリファイルがある場所が決め打ちされている

build.shの中でsedを利用されていると思います。
このsedのバイナリファイルが`/usr/bin/sed`に配置されている前提となっていましたが、`/bin/sed`に配置されている環境であったので、動かない問題がありました。

```bash
$ which sed
/bin/sed
```

以下のように、バイナリファイルのフルパスを指定しなくても動くことは確認出来ました。
(フルパスを指定しないと動かない環境がある？)

```diff
- e=$(echo $t | /usr/bin/sed 's/^.*\.\([^\.]*\)$/\1/')
+ e=$(echo $t | sed 's/^.*\.\([^\.]*\)$/\1/')
```

これからのスクリプトを作る際の参考にしていただければと思います。

**Comment by Hiroya-W** [comment]
また、面白いライブラリだったので、折角なのでbuildスクリプトをCMake化して使えるようにしてみました。
Pull Request出しておきますので、良ければ参考にするなり、使ってください。
(ディレクトリ構造から変えていじっているので、マージするかどうかの判断はおまかせします)

CMake化すると、これを利用した別のプロジェクトで利用しやすくなって良いかもです。
これは、試しに作ってみたサンプルプロジェクトです。
https://github.com/Hiroya-W/NeoC-sample-project

**Comment by RotationE** [comment]
諸々、感謝至極です...! 勉強になります
